version: "3.4"

services:
  diffusion:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - /home/mohitm/datasets/stanford_cars/cars_train:/app/data/cars_train
      - /home/mohitm/datasets/stanford_cars/cars_test:/app/data/cars_test
      - .:/app

    command: [ "python", "training.py" ]
